HashMap source code
kuyanov/hashmap pull request #1
Opened 2021-03-05 11:24 UTC by kuyanov

Куянов Фёдор
Контест - 24924
Задача A
Сабмит - https://official.contest.yandex.ru/contest/24924/run-report/48954541/

2021-06-22 22:08 UTC, glebshp requested changes

2021-06-22 22:08 UTC, glebshp commented on .gitignore
>  *.exe
а зачем нам все эти файлы кроме .h ?

2021-06-22 22:08 UTC, glebshp commented on hash_map.h
> +// Hash table with separate chaining, dynamic expansion.
Такого описания недостаточно, больше информации об устройстве, стратегии масштабирования и том почему линейное итерирование.

И приложить ещё ссылку на подробное описание алгоритма, можно на википедии

2021-06-22 22:08 UTC, glebshp commented on hash_map.h
> +    Hash hasher;
приватные поля не должны идти в начале, в первую очередь читающему класс интересны его публичные методы

2021-06-22 22:08 UTC, glebshp commented on hash_map.h
> +    std::list<ConstKeyVal> all;
почему у приватных полей такой же способ написания имён, как у публичных методов?

2021-06-22 22:08 UTC, glebshp commented on main.cpp
> +//
лишний файл

2021-06-22 22:08 UTC, glebshp commented on hash_map.h
> +        size_t id = bucket_id(key);
дублирование кода из find

2021-06-22 22:36 UTC, kuyanov commented on .gitignore
>  *.exe
А как тестировать иначе?

2021-06-23 23:19 UTC, glebshp requested changes

2021-06-23 23:19 UTC, glebshp commented on .gitignore
>  *.exe
нет, тестировать то ОК, но в репозиторий на гитхабе добавлять не нужно

2021-06-23 23:19 UTC, glebshp commented on hash_map.h
> +            resize(2 * table.size());
управляющая константа должна быть отдельной публичной константой (constexpr) класса

2021-06-23 23:19 UTC, glebshp commented on hash_map.h
> +        resize(2 * allSize);
коммент ниже применить ко всем константам 2

2021-06-23 23:19 UTC, glebshp commented on hash_map.h
> +        table.resize(other.table.size());
получается, что мы при копировании создаём таблицу не из нужного числа бакетов, а из того сколько было в копируемой, а оно могло оказаться значительно больше, чем реальное число элементов там

например, можно за линейное число действий создать набор таблиц, которые сожрут квадрат памяти

2021-06-24 23:02 UTC, glebshp requested changes

2021-06-24 23:02 UTC, glebshp commented on .gitignore
>  *.out
Так а можно уже убрать из коммита всё кроме .h ?

2021-06-24 23:02 UTC, glebshp commented on hash_map.h
> +// All queries work for O(length of chain) which is O(1) in average.
on average

2021-06-24 23:02 UTC, glebshp commented on hash_map.h
> +        initBuckets(allSize);
получается, что мы сразу создаём заполненную таблицу, и с ближайшей вставкой будем её пересоздавать

2021-06-25 19:11 UTC, glebshp approved these changes

2021-06-25 19:13 UTC, merged